<a href="https://colab.research.google.com/github/alvaroalon2/NER4COVID/blob/main/NER4COVID.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers==3.0.0

     |████████████████████████████████| 757kB 17.3MB/s 
     |████████████████████████████████| 3.0MB 56.4MB/s 
     |████████████████████████████████| 1.2MB 55.0MB/s 
     |████████████████████████████████| 870kB 52.2MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.44-cp37-none-any.whl size=886084 sha256=144c12e7b8a7cf04679fce4a9387f2393e35907c61d437c112fb9905e6912248
  Stored in directory: /root/.cache/pip/wheels/3e/fb/c0/13ab4d63d537658f448366744654323077c4d90069b6512f3c
Successfully built sacremoses


In [ ]:
!pip install transformers==4.5.0

In [ ]:
!pip uninstall torchsummary -y
!pip install torchsummaryX
from torchsummaryX import summary

Uninstalling torchsummary-1.5.1:
  Successfully uninstalled torchsummary-1.5.1


In [ ]:
!pip install wget

  Created wheel for wget: filename=wget-3.2-cp37-none-any.whl size=9681 sha256=ef3e438b37f5cebd56b13dfce73caf64ec08935ebbae017d3f9971bb279453ee
  Stored in directory: /root/.cache/pip/wheels/40/15/30/7d8f7cea2902b4db79e3fea550d7d7b85ecb27ef992b618f3f
Successfully built wget


In [ ]:
!pip install seqeval

In [ ]:
!git clone https://github.com/dmis-lab/biobert-pytorch.git

Cloning into 'biobert-pytorch'...
remote: Enumerating objects: 211, done.
remote: Counting objects: 100% (211/211), done.
remote: Compressing objects: 100% (184/184), done.
remote: Total 211 (delta 43), reused 169 (delta 15), pack-reused 0
Receiving objects: 100% (211/211), 1.91 MiB | 11.58 MiB/s, done.
Resolving deltas: 100% (43/43), done.


In [ ]:
%cd biobert-pytorch

/content/biobert-pytorch


In [ ]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive/MyDrive/TFM/

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive/MyDrive/TFM


In [ ]:
%cd named-entity-recognition/

/gdrive/My Drive/TFM/named-entity-recognition


In [ ]:
from transformers import AutoTokenizer, AutoModel, AutoConfig, AutoModelForTokenClassification
from transformers import BertTokenizer, BertModel, BertTokenizerFast
from transformers import TokenClassificationPipeline
from torch.nn import functional as F
from torch import nn
import torch
import tensorflow as tf
import os
from typing import Dict

In [ ]:
os.environ['DATA_DIR'] = "../datasets/NER"
os.environ['ENTITY'] = "NCBI-disease"
os.environ['SAVE_DIR'] = './output'
os.environ['MAX_LENGTH']= '192'
os.environ['BATCH_SIZE']= '32'
os.environ['NUM_EPOCHS']= '30'
os.environ['SAVE_STEPS']= '1000'
os.environ['SEED']= '1'

# Preparing GPU

In [ ]:
# Get the GPU device name.
device_name = tf.test.gpu_device_name()

# The device name should look like the following:
if device_name == '/device:GPU:0':
    print('Found GPU at: {}'.format(device_name))
else:
    raise SystemError('GPU device not found')

Found GPU at: /device:GPU:0


In [ ]:
# If there's a GPU available...
if torch.cuda.is_available():    

    # Tell PyTorch to use the GPU.    
    device = torch.device("cuda")

    print('There are %d GPU(s) available.' % torch.cuda.device_count())

    print('We will use the GPU:', torch.cuda.get_device_name(0))

# If not...
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

There are 1 GPU(s) available.
We will use the GPU: Tesla T4


In [ ]:
!nvidia-smi

Mon Apr 12 10:16:30 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.67       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P0    57W / 149W |    124MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# TRAINING

In [ ]:
!python run_ner.py \
    --data_dir ${DATA_DIR}/${ENTITY}/ \
    --labels ${DATA_DIR}/${ENTITY}/labels.txt \
    --model_name_or_path dmis-lab/biobert-base-cased-v1.1 \
    --output_dir ${SAVE_DIR}/${ENTITY} \
    --max_seq_length ${MAX_LENGTH} \
    --num_train_epochs ${NUM_EPOCHS} \
    --per_device_train_batch_size ${BATCH_SIZE} \
    --save_steps ${SAVE_STEPS} \
    --seed ${SEED} \
    --do_train \
    --do_eval \
    --do_predict \
    --overwrite_output_dir

Se han truncado las últimas 5000 líneas del flujo de salida.
Iteration:  58% 115/199 [04:13<02:38,  1.89s/it]
Iteration:  58% 116/199 [04:15<02:36,  1.89s/it]
Iteration:  59% 117/199 [04:17<02:34,  1.89s/it]
Iteration:  59% 118/199 [04:19<02:33,  1.89s/it]
Iteration:  60% 119/199 [04:21<02:31,  1.89s/it]
Iteration:  60% 120/199 [04:23<02:29,  1.89s/it]
Iteration:  61% 121/199 [04:25<02:27,  1.89s/it]
Iteration:  61% 122/199 [04:27<02:25,  1.89s/it]
Iteration:  62% 123/199 [04:28<02:23,  1.89s/it]
Iteration:  62% 124/199 [04:30<02:21,  1.89s/it]
Iteration:  63% 125/199 [04:32<02:19,  1.89s/it]
Iteration:  63% 126/199 [04:34<02:17,  1.89s/it]
Iteration:  64% 127/199 [04:36<02:15,  1.89s/it]
Iteration:  64% 128/199 [04:38<02:14,  1.89s/it]
Iteration:  65% 129/199 [04:40<02:11,  1.89s/it]
Iteration:  65% 130/199 [04:42<02:10,  1.88s/it]
Iteration:  66% 131/199 [04:44<02:08,  1.89s/it]
Iteration:  66% 132/199 [04:45<02:06,  1.89s/it]
Iteration:  67% 133/199 [04:47<02:04,  1.89s/it]
Iteratio

In [ ]:
!ls output/NCBI-disease

checkpoint-4000   pytorch_model.bin	   tokenizer_config.json
checkpoint-5000   special_tokens_map.json  training_args.bin
config.json	  test_predictions.txt	   vocab.txt
eval_results.txt  test_results.txt


#TESTING

In [ ]:
!python run_ner.py \
    --data_dir ${DATA_DIR}/${ENTITY}/ \
    --labels ${DATA_DIR}/${ENTITY}/labels.txt \
    --model_name_or_path output/NCBI-disease \
    --output_dir ${SAVE_DIR}/${ENTITY} \
    --max_seq_length ${MAX_LENGTH} \
    --seed ${SEED} \
    --do_eval \
    --do_predict

2021-04-13 11:49:53.901833: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
04/13/2021 11:49:57 - INFO - transformers.training_args -   PyTorch: setting up devices
04/13/2021 11:49:57 - WARNING - __main__ -   Process rank: -1, device: cuda:0, n_gpu: 1, distributed training: False, 16-bits training: False
04/13/2021 11:49:57 - INFO - __main__ -   Training/evaluation parameters TrainingArguments(output_dir='./output/NCBI-disease', overwrite_output_dir=False, do_train=False, do_eval=True, do_predict=True, evaluate_during_training=False, per_device_train_batch_size=8, per_device_eval_batch_size=8, per_gpu_train_batch_size=None, per_gpu_eval_batch_size=None, gradient_accumulation_steps=1, learning_rate=5e-05, weight_decay=0.0, adam_epsilon=1e-08, max_grad_norm=1.0, num_train_epochs=3.0, max_steps=-1, warmup_steps=0, logging_dir='runs/Apr13_11-49-56_adfa6e221848', logging_first_step=False, logging_steps=500, save_steps=500

# Use of Model

In [ ]:
labels = ["B-bio", "I-bio","O"]
label_map: Dict[int, str] = {i: label for i, label in enumerate(labels)}
num_labels = len(labels)

In [ ]:
label_map

{0: 'B-bio', 1: 'I-bio', 2: 'O'}

In [ ]:
config_name = 'output/NCBI-disease'
tokenizer_name = 'output/NCBI-disease'
model_name_or_path = 'output/NCBI-disease'

In [ ]:
config = AutoConfig.from_pretrained(
        config_name,
    )

tokenizer = AutoTokenizer.from_pretrained(
        tokenizer_name,
        use_fast=True,
        return_offsets_mapping=True
    )

model = AutoModelForTokenClassification.from_pretrained(
        model_name_or_path,
        config=config
    )

In [ ]:
model.config

BertConfig {
  "_num_labels": 3,
  "architectures": [
    "BertForTokenClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "B-bio",
    "1": "I-bio",
    "2": "0"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "B-bio": 0,
    "I-bio": 1,
    "O": 2
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "type_vocab_size": 2,
  "vocab_size": 28996
}

In [ ]:
NER_inference = TokenClassificationPipeline(model= model,tokenizer=tokenizer, framework='pt', task='ner', grouped_entities=True)

In [ ]:
sequence = 'Pneumonia and Diphtheria are one of the commonest infections in elderly patients, also Influenza'

In [ ]:
prueba = NER_inference(sequence)

In [ ]:
prueba

[{'end': 9,
  'entity_group': 'bio',
  'score': 0.9869390726089478,
  'start': 0,
  'word': 'Pneumonia'},
 {'end': 13,
  'entity_group': '0',
  'score': 0.9999927282333374,
  'start': 10,
  'word': 'and'},
 {'end': 24,
  'entity_group': 'bio',
  'score': 0.9855318069458008,
  'start': 14,
  'word': 'Diphtheria'},
 {'end': 86,
  'entity_group': '0',
  'score': 0.9999937812487284,
  'start': 25,
  'word': 'are one of the commonest infections in elderly patients, also'},
 {'end': 96,
  'entity_group': 'bio',
  'score': 0.8170945942401886,
  'start': 87,
  'word': 'Influenza'}]

In [ ]:
class Entities:
  
  def __init__(self, result, text):
    self. result = result
    self.text = text
    self.ents = dict()
    
    self.obtain_ents()

  def obtain_ents(self):
    self.ents = [{"start": ent['start'],
                              "end": ent['end'],
                              "label": ent['entity_group']
                  } for ent in self.result if ent['entity_group'] != '0']
    
  def parse_ner_spacy(self):
    dict_results = {
        "text": self.text,
        "ents": self.ents,
        "title": None
    }
    return dict_results
  
  


In [ ]:
entidades= Entities(result,text)

In [ ]:
entidades.text[460:470]

'r thromboc'

In [ ]:
ex = entidades.parse_ner_spacy()

In [ ]:
import spacy
from spacy import displacy
from IPython.core.display import display, HTML

options = {"colors": {"bio": "blue"}}

html = displacy.render(ex, style="ent", manual=True,options=options)
display(HTML(html))

In [ ]:
with open('prueba.txt','r') as f:
  text = f.read()

In [ ]:
print(text[460:470])

r thromboc


In [ ]:
result = NER_inference(text)

# Model preparation

In [ ]:
MAX_LEN = 128
PRETRAINED_MODEL = 'microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext'

In [ ]:
class BioBert_NER(nn.Module):

   def __init__(self, n_classes):
       super(BioBert_NER, self).__init__()
       self.config = AutoConfig.from_pretrained("microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext", finetuning_task="ner",base_model_prefix='ner')
       self.bert = BertModel.from_pretrained(PRETRAINED_MODEL, config=config)
       self.out = nn.Linear(self.bert.config.hidden_size, n_classes)

   def forward(self, input_ids, attention_mask):
      #  _, output = self.bert(**input)
      _, pooled_output = self.bert(
      input_ids=input_ids,
      attention_mask=attention_mask, return_dict=False)
      out = self.out(pooled_output)
      return out

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(PRETRAINED_MODEL)

In [ ]:
NER_model = BioBert_NER(4)
NER_model = NER_model.to(device)

In [ ]:
encoded_text = tokenizer.encode_plus(
  text1,
  max_length=MAX_LEN,
  add_special_tokens=True,
  return_token_type_ids=False,
  padding='max_length',
  return_attention_mask=True,
  return_tensors='pt',
)

In [ ]:
input_ids = encoded_text['input_ids'].to(device)
attention_mask = encoded_text['attention_mask'].to(device)

In [ ]:
attention_mask

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]], device='cuda:0')

In [ ]:
output = NER_model(input_ids, attention_mask)
_, prediction = torch.max(output, dim=1)

In [ ]:
output

tensor([[0.2283, 0.0066, 0.2447, 0.2136]], device='cuda:0',
       grad_fn=<AddmmBackward>)

In [ ]:
summary(NER_model, torch.zeros((128, 1), dtype=torch.long))

In [ ]:
print(NER_model)

In [ ]:
NER_inference = TokenClassificationPipeline(model= NER_model,tokenizer=tokenizer, framework='pt', task='ner')

AttributeError: ignored

# Pruebas

In [ ]:
config = model = AutoConfig.from_pretrained("microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext", finetuning_task="ner",base_model_prefix='ner')

In [ ]:
config

BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": "ner",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.4.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext")

model = AutoModelForTokenClassification.from_pretrained("microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext", config = config)

Some weights of the model checkpoint at microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext were not used when initializing BertForTokenClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.decoder.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForToken

In [ ]:
print('tokenizer type:', type(tokenizer))
print('model type:', type(model))

tokenizer type: <class 'transformers.models.bert.tokenization_bert_fast.BertTokenizerFast'>
model type: <class 'transformers.models.bert.modeling_bert.BertForTokenClassification'>


In [ ]:
text1 = "Hydrogels are hydrophilic polymer networks which may absorb from " \
       "10–20% (an arbitrary lower limit) up to thousands of times their " \
       "dry weight in water."

In [ ]:
text2 = "SARS-CoV-2 variants of concern (VOC) have arisen independently at multiple locations [1, 2]" \
        "and may reduce the efficacy of current vaccines targeting the spike glycoprotein [3]. Here, using a live virus neutralization assay (LVNA)," \
        " we compared neutralization of a non-VOC variant versus the 501Y.V2 variant using plasma collected from adults hospitalized with COVID-19" \
        " from two South African infection waves, with the second wave dominated by 501Y.V2 infections."

In [ ]:
tokens = tokenizer.tokenize(text2)

In [ ]:
encoding = tokenizer.encode_plus(text1, add_special_tokens = True,    truncation = True, padding = "max_length", return_attention_mask = True, return_tensors = "pt")

Asking to pad to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no padding.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


In [ ]:
encoding

{'input_ids': tensor([[    2, 14917,  2032, 14033,  4593,  5849,  2154,  2278,  7322,  2037,
          2119,   229,  2036,     9,    12,  1925, 14346,  2826,  4411,    13,
          2353,  1942, 16034,  1927,  3586,  2310,  7143,  3388,  1922,  3224,
            18,     3]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
tokenizer.convert_ids_to_tokens(encoding['input_ids'][0])

['[CLS]',
 'hydrogels',
 'are',
 'hydrophilic',
 'polymer',
 'networks',
 'which',
 'may',
 'absorb',
 'from',
 '10',
 '–',
 '20',
 '%',
 '(',
 'an',
 'arbitrary',
 'lower',
 'limit',
 ')',
 'up',
 'to',
 'thousands',
 'of',
 'times',
 'their',
 'dry',
 'weight',
 'in',
 'water',
 '.',
 '[SEP]']

In [ ]:
encoding2 = tokenizer.encode(text1, return_tensors = "pt")

In [ ]:
encoding2

tensor([[    2, 14917,  2032, 14033,  4593,  5849,  2154,  2278,  7322,  2037,
          2119,   229,  2036,     9,    12,  1925, 14346,  2826,  4411,    13,
          2353,  1942, 16034,  1927,  3586,  2310,  7143,  3388,  1922,  3224,
            18,     3]])

In [ ]:
for token in tokens:
  print(token + '\n')

sars

-

cov

-

2

variants

of

concern

(

voc

)

have

arisen

independently

at

multiple

locations

[

1

,

2

]

and

may

reduce

the

efficacy

of

current

vaccines

targeting

the

spike

glycoprotein

[

3

]

.

here

,

using

a

live

virus

neutralization

assay

(

lv

##na

)

,

we

compared

neutralization

of

a

non

-

voc

variant

versus

the

501

##y

.

v2

variant

using

plasma

collected

from

adults

hospitalized

with

cov

##id

-

19

from

two

south

african

infection

waves

,

with

the

second

wave

dominated

by

501

##y

.

v2

infections

.



In [ ]:
output = model(**encoding) 

In [ ]:
softmax = F.softmax(output.last_hidden_state, dim=-1)

In [ ]:
softmax

tensor([[[0.0013, 0.0013, 0.0013,  ..., 0.0010, 0.0020, 0.0016],
         [0.0012, 0.0017, 0.0012,  ..., 0.0011, 0.0019, 0.0013],
         [0.0014, 0.0017, 0.0017,  ..., 0.0015, 0.0011, 0.0017],
         ...,
         [0.0011, 0.0015, 0.0012,  ..., 0.0011, 0.0012, 0.0017],
         [0.0011, 0.0013, 0.0012,  ..., 0.0011, 0.0013, 0.0015],
         [0.0011, 0.0013, 0.0012,  ..., 0.0011, 0.0013, 0.0015]]],
       grad_fn=<SoftmaxBackward>)